### ISSUE TITLE
Support PortalEntry display priorities

### ISSUE THREAD

**Issue by YeungKC** [rrousselGit/flutter_portal#27] opened 2021-02-24 18:06 UTC
I use the portal to implement a widget that is displayed only when hovering, and when I right-click on the widget I need to display the context menu, but the context menu is displayed at a level below the hovering widget.

I would like to be able to configure the priority.

**Comment by fzyzcjy** [comment] 2022-03-10 14:17
Sounds like duplicate of https://github.com/rrousselGit/flutter_portal/issues/39

**Closed by fzyzcjy** 2022-03-10 14:17 UTC
Labels: enhancement
